---
# daliuge_node-mgr/tasks/main.yml
#
#- name: Apply customised DALiuGE Node Manager configuration
#  template:
#    src: daliuge-node.conf.j2
#    dest: /etc/slurm/slurm.conf
#    owner: root
#    group: root
#    mode: 0644
#  notify:
#    - Restart SLURM service

#- name: Install OpenHPC compute image packages
#  yum:
#    name: "@ohpc-base-compute"
#    state: installed

#- name: Install OpenHPC SLURM client packages
#  yum:
#    name: "@ohpc-slurm-client"
#    state: installed

- copy:
    src: daliuge/etc/init-scripts/dlg-nm
    dest: /etc/init.d/dlg-nm
    remote_src: yes

- name: Select the DALiuGE service to control
  set_fact:
    daliuge_service: dlg_nm

#- name: Install OpenHPC LMOD
#  yum:
#    name: "lmod-ohpc"
#    state: installed
