---
- name: Copy ifcfg-ib0 network script over
  template:
    src: ifcfg-ib0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-ib0
  become: True

- name: Bring ib0 down
  command: ifdown ib0
  become: True

- name: Bring ib0 up
  command: ifup ib0
  become: True

...
