---
- name: Restart NetworkManager service
  systemd:
    name: NetworkManager
    enabled: true
    state: restarted
  become: true

- name: Reset interface
  import_tasks: reset_interface.yml
  become: true
...
