---
# Update and/or install pip packages
- pip:
    name: pip setuptools
    state: latest

# Remove any old copy of DALiuGE
- file:
    path: daliuge
    state: absent

# Clone the DALiuGE git reo
#  command: git clone --branch {{ daliuge_version }} https://github.com/ICRAR/daliuge.git
- git:
    repo: https://github.com/ICRAR/daliuge.git
    dest: daliuge
    version: "{{daliuge_version}}"

# Install DALiuGE
- pip:
    name: .
    chdir: daliuge/
    state: latest

- name: Apply customised DALiuGE configuration
  template:
    src: dlg.options.j2
    dest: /etc/sysconfig/dlg
    owner: root
    group: root
    mode: 0644
# Don't need these at the moment as they are started elsewhere
#  notify:
#    - Restart DALiuGE service
