---
- name: Update and/or install pip packages
  command: pip install -U pip setuptools

#- name: Remove any old copy of DALiuGE
#  command: rm -rf daliuge

- name: Delete DALiuGE directory
  - file: path=daliuge recurse=yes state=absent

- name: Clone the DALiuGE git reo
  command: git clone --branch v0.3.2 https://github.com/ICRAR/daliuge.git

- name: Install DALiuGE
  command: pip install -U .
  args:
      chdir: daliuge/

- copy:
    src: daliuge/etc/init-scripts/dlg-dim
    dest: /etc/init.d/dlg-dim
    remote_src: yes

- copy:
    src: daliuge/etc/init-scripts/dlg-nm
    dest: /etc/init.d/dlg-nm
    remote_src: yes

- name: Apply customised DALiuGE configuration
  template:
    src: dlg.options.j2
    dest: /etc/sysconfig/dlg
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart DALiuGE service

#- name: Ensure the SLURM spool directory exists
#  file:
#    path: /var/spool/slurm
#    owner: slurm
#    group: slurm
#    mode: 0755
#    state: directory

#- name: Ensure SLURM services are enabled
#  service:
#    name: "{{slurm_service}}"
#    enabled: yes
#  notify:
#    - Restart SLURM service

#- name: Apply customised SLURM configuration
#  template:
#    src: slurm.conf.j2
#    dest: /etc/slurm/slurm.conf
#    owner: root
#    group: root
#    mode: 0644
#  notify: 
#    - Restart SLURM service
