---
- name: Install developments tools envrironment group
  yum:
    name: "@^Development Tools"
    state: installed

- name: Ensure selected OpenHPC packages are installed
  yum:
    name: "{{item}}"
    state: present
  with_items: "{{openhpc_packages}}"
