---
# This name is used for the Heat stack and as a prefix for the
# cluster node hostnames.
cluster_name: gpu

# This parameter should be set to the name of an RSA keypair you have
# uploaded to OpenStack.
cluster_keypair: wendy

# Site-specific network configuration.
cluster_net:
  - { net: "ilab", subnet: "ilab" }
  - { net: "p3-lln", subnet: "p3-lln" }
  - { net: "p3-bdn", subnet: "p3-bdn" }

# Default nodenet to use for all instances in the cluster
cluster_nodenet_resource: "Cluster::NodeNet3"

# Enable the use of config drive, for managing IP assignment on IPoIB
cluster_config_drive: true

# GPU images do not have infiniband packages built in so run this
# playbook to ensure it is enabled.
configure_ib_enabled: true

# The cluster consists of a single compute group.
cluster_groups:
  - "{{ compute }}"

compute:
  name: "compute"
  flavor: "compute-GPU"
  image: "CentOS7.6-CUDA"
  num_nodes: 2
  user: "centos"

# Node group assignments for cluster roles.
# These group assignments are appended to the cluster inventory file.
# The names of these roles are cross-referenced to groups referred to
# in playbooks in the ansible/ directory.
cluster_roles:
  - name: "login"
    groups: [ "{{ compute }}" ]
  - name: "ceph_client"
    groups: [ "{{ compute }}" ]
  - name: "glusterfs_client"
    groups: [ "{{ compute }}" ]
  - name: "beegfs_client"
    groups: ["{{ compute }}" ]

# Choose between glusterfs, beegfs and none.
cluster_fs: beegfs

# Config for Ceph mount
ceph_mount_enabled: true
ceph_mount_fuse: false

# BeegFS config
beegfs_state: present
beegfs_force_format: no
beegfs_interfaces:
- ib0
beegfs_client:
- path: "/mnt/openhpc"
  port: 8004
  mgmt_host: "openhpc-login-0"
- path: "/mnt/storage-ssd"
  port: 18004
  mgmt_host: "storage-ssd-node-0"
- path: "/mnt/storage-nvme"
  port: 28004
  mgmt_host: "storage-nvme-node-0"

extra_packages:
- bison
- flex
- gcc-gfortran
- blas-devel
- lapack-devel
...
