---
# This name is used for the Heat stack and as a prefix for the
# cluster node hostnames.
cluster_name: gpu

# This parameter should be set to the name of an RSA keypair you have
# uploaded to OpenStack.
cluster_keypair: wendy

# Site-specific network configuration.
cluster_net:
  - { net: "ilab", subnet: "ilab" }
  - { net: "p3-lln", subnet: "p3-lln" }
  - { net: "p3-bdn", subnet: "p3-bdn" }

# Default nodenet to use for all instances in the cluster
cluster_nodenet_resource: "Cluster::NodeNet3"

# Enable the use of config drive, for managing IP assignment on IPoIB
cluster_config_drive: true

# The cluster consists of a single compute group.
cluster_groups:
  - "{{ compute }}"

compute:
  name: "compute"
  flavor: "compute-GPU"
  image: "CentOS7.6-CUDA"
  num_nodes: 2
  user: "centos"

# Node group assignments for cluster roles.
# These group assignments are appended to the cluster inventory file.
# The names of these roles are cross-referenced to groups referred to
# in playbooks in the ansible/ directory.
cluster_roles:
  - name: "glusterfs_server"
    groups: [ "{{ compute }}" ]
  - name: "glusterfs_client"
    groups: [ "{{ compute }}" ]
  - name: "beegfs_oss"
    groups: [ "{{ compute }}" ]
  - name: "beegfs_client"
    groups: ["{{ compute }}" ]

# Choose between glusterfs, beegfs and none.
cluster_fs: beegfs

# Config for Ceph mount
ceph_mount_enabled: false
ceph_mount_fuse: false

# BeegFS config
beegfs_state: present
beegfs_force_format: no
beegfs_interfaces:
- ib0
beegfs_client:
- path: "/mnt/openhpc"
  port: 8004
  mgmt_host: "openhpc-login-0"
- path: "/mnt/storage-ssd"
  port: 18004
  mgmt_host: "storage-ssd-node-0"
- path: "/mnt/storage-nvme"
  port: 28004
  mgmt_host: "storage-nvme-node-0"

# GPU users
users:
- username: ben
  name: Ben Mort
  groups: ['wheel','systemd-journal']
  uid: 1005
  ssh_key:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCeGbpm1SHEdEEquMw+xyrZ0TqULQ1aL4LuDsbF3NQedAxyg+1/PvY3/+HwSs8dZUlP/DGVrgPdP7JEfKi14oF4TQ6oIy89bKkH0QUF5DkIP8g6cHTZZjZxw1Gso47N636u1qw46dSKiBrYFMmEzRMbPVOWGzxdYHP6FSryrl6YiDtiegBA6/j6lM3a0DdUHtV10KhU58NyNl4MSVyQrayqYtlqZK05QFQ47lpE8FHU0Ud6AHB4W4D8Hy0lbUeIVN+S9xZWKRvCmyQSeIX9mLL3rAvDgFYLbGxYCQ4GTnG1U/Ky2CpZBh1n5ihtDINuXDN0uk9YWNMtAGjm4YUqhSopgLKC3EY/fXtZ28Nr3AMtggBD+vY+FnemSFegoTzKwExmTDBEAzTjZK40parklOBQYimgy4iBeD7//iVis/RFKw1vAKLUCPKkx/eSkLhr9e1IqzKcPIWF4hYVRTGMdM42ziJZ/DHiGcOWKRxDzdhM/wT8SZ0xN7H5h8g7pn+SAmWQETLX4I2qvY2qXx0RcoXzB/cNvAOqxtXFTYZZi1nhzZ4u4S6hD1zOalxg6r5CT5VgqL5AHoe3EmFcvD5t0loGWO1e7CqHV0KOCj9jzOTju+BlQbZEPo8zcZfWlpE+s807NkRDqr1Obg2Sbc6kPPtGlNJcxlDMQymHTPnxgH4e9Q== hpcmort1@ilab-gate.ilab.cluster"
...
