---
# SIP network interface names
ext_name: ilab
bdn_name: p3-bdn
lln_name: p3-lln

# SIP configuration
cluster_user: "fedora"
cluster_name: "k8s-kata"
cluster_template_name: "k8s-fedora-atomic-27"
cluster_keypair: "wendy"
cluster_coe: "kubernetes"
cluster_default_interface: "{{ ext_name }}"
cluster_interfaces:
- "{{ ext_name }}"
- "{{ lln_name }}"
- "{{ bdn_name }}"

cluster_master_group:
  name: "master"
  count: 1

cluster_worker_group:
  name: "minion"
  count: 2

cluster_groups:
- "{{ cluster_master_group }}"
- "{{ cluster_worker_group }}"

cluster_roles:
- name: "{{ cluster_coe }}"
  groups: "{{ cluster_groups }}"
- name: "ceph_client"
  groups: "{{ cluster_groups }}"

# Kubernetes version
cluster_k8s_version: "v1.14.0"
cluster_k8s_master_kubelet: true

# Manila mount config
ceph_mount_share_name: "HomeDirs"
ceph_mount_fuse: false

# Override alaska_homedir as Fedora Atomic doesn't allow folders to be created under root scope
alaska_homedir: "/mnt/alaska"

# Disable these before running setup.yml
kdump_enable: false
# This is enabled by default on Atomic Host
setup_time_enable: false

# SIP users 
users:
- username: bharat
  name: Bharat Kunwar
  groups: ['wheel','systemd-journal']
  password:
  uid: 1004
  ssh_key:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDT7FfKdhVmT/HturOK6sLRKcqFYDnfbKWVE8Lv+KntJCBN0pGk5PECCmmA7/5JzAzfba4nmMpI20byJ0VCphzTbYFHtsZNd6Ci4NIKb5GrxP1f9RN3BYlmm1rJ5OgoXjvg0VpUiUnkLsVYkHfzUTx6tDHj8zV2DQYWGg2BtZk8YSEnigK6ppZcBuRwhY1wmKEodeXus6vik20v+PGDAlSmSlhHsYUOe8/GNhs6fZ9a9XEVHw/pPxYa3HmNGgUiJYOxSA0DLq8HzxQDoSgpMMeG2bD36DsHSnnbLNUtH3+DmveX2FxWWHRKG4IgW5O0UdLcGzrakZ6OFi/bUL0bBge7 bharat@dev-director.dev-cluster.hpc.cam.ac.uk"

# SIP sudoers
sudoers_sudoers:
  privileges:
  - name: "%wheel"
    entry: "ALL=NOPASSWD:ALL"
...
