---
# WARNING: This is a test cluster intended to be invoked via the scripts inside
# tests/ folder. Do not invoke  directly.

# This name is used for the Heat stack and as a prefix for the
# cluster node hostnames.
cluster_name: test-openhpc

# Login node configuration.
slurm_login_flavor: "compute-A"
slurm_login_num_nodes: 1

# Compute node configuration.
slurm_compute_flavor: "compute-A"
slurm_compute_num_nodes: 1

# Choose between glusterfs, beegfs and none.
cluster_fs: none

# Don't create any software RAID arrays.
mdadm_arrays: []
...
