---
# daliuge_isl-mgr/tasks/main.yml
#
#- name: Apply customised DALiuGE Island Manager configuration
#  template:
#    src: daliuge-node.conf.j2
#    dest: /etc/slurm/slurm.conf
#    owner: root
#    group: root
#    mode: 0644
#  notify:
#    - Restart SLURM service

#- name: Install OpenHPC master SLURM packages
#  yum:
#    name: "@ohpc-slurm-server"
#    state: installed

- copy:
    src: daliuge/etc/init-scripts/dlg-dim
    dest: /etc/init.d/dlg-dim
    remote_src: yes
    owner: root
    group: root
    mode: 0755

- name: Select the DALiuGE service to control
  set_fact:
    daliuge_service: dlg_dim