---

- name: Retrieve the firmware image from Dell downloads site
  get_url:
    url: "{{ dell_bios_url }}"
    dest: "/tmp"
    mode: 0755
  register: bios_data

# Exit codes:
# 2: Update applied.
# 3: No update required.
- name: Execute the BIOS firmware upgrade
  command: "{{ bios_data.dest }} -q"
  become: True
  register: result
  failed_when: result.rc not in [2, 3]
  changed_when: result.rc == 2

- name: Remove the BIOS firmware image
  file:
    path: "{{ bios_data.dest }}"
    state: absent

- name: Retrieve the firmware image from Dell downloads site
  get_url:
    url: "{{ dell_idrac_url }}"
    dest: "/tmp"
    mode: 0755
  register: idrac_data

# Exit codes:
# 0: Update applied, reboot required.
# 3: No update required.
- name: Execute the iDRAC firmware upgrade
  command: "{{ idrac_data.dest }} -q"
  become: True
  register: result
  failed_when: result.rc not in [0, 3]
  changed_when: result.rc == 0

- name: Remove the iDRAC firmware image
  file:
    path: "{{ idrac_data.dest }}"
    state: absent
