---
- hosts: cluster
  roles:
  - role: stackhpc.beegfs
    beegfs_enable:
      mgmt: no
      admon: no
      meta: no
      oss: no
      client: "{{ inventory_hostname in groups['cluster_beegfs_client'] }}"
...
