---
# This playbook uses the Ansible OpenStack modules to create a cluster
# using a number of baremetal compute node instances, and configure it
# for a SLURM partition
- hosts: openstack
  roles:
    - role: stackhpc.cluster-infra
      cluster_name: "{{ cluster_name }}"
      cluster_params:
        cluster_prefix: "{{ cluster_name }}"
        cluster_keypair: "{{ cluster_keypair }}"
        cluster_groups: "{{ cluster_groups }}"
        cluster_net: "{{ cluster_net }}"
        cluster_config_drive: "{{ cluster_config_drive | default(false) }}"
        nodenet_resource: "{{ cluster_nodenet_resource | default(omit) }}"
      cluster_roles: "{{ cluster_roles | default([]) }}"
