# This role ensured that cluster_admins are configured as defined.
- hosts: cluster
  vars:
  become: yes
  roles:
  - role: singleplatform-eng.users
    users: "{{ alaska_admins + extra_admins | default([]) }}"
