# run using:
# cd <repo-root>
# ansible-playbook -e @config/openhpc.yml ansible/deploy-tf.yml

- hosts: localhost
  gather_facts: false
  tasks:
    # we want to provide a single, nested, "config" var to tf, so add nesting here:
    # NB: this actually gets ALL the hostvars, not just the config, but this is actually useful
    - set_fact:
        tf_config:
          config: "{{ hostvars[inventory_hostname] }}"
    # work around ansible's broken provision of vars to terraform: https://github.com/ansible/ansible/issues/51687
    - tempfile:
        state: file
        suffix: ".tfvars.json"
      register: tmp_tfvars_file
    - copy:
        dest: "{{ tmp_tfvars_file.path }}"
        content: "{{ hostvars[inventory_hostname]['tf_config'] | to_json }}"
    - debug:
        msg: "temporary tfvars file created at {{ tmp_tfvars_file.path }}"
    - terraform:
        project_path: ../tf_ohpc/ # undocumented, needs to have a / in it!
        variables_file: "{{ tmp_tfvars_file.path }}"
      register: tf_cmd
    - debug:
        msg: "{{ tf_cmd.stdout }}"
        