---
# Query OpenStack Manila for details aob
- hosts: localhost
  roles:
    - role: stackhpc.os-manila-mount
      os_manila_mount_action: "lookup"
      os_manila_mount_share_name: "HomeDirs"
      os_manila_mount_share_user: "home"

- hosts: container-infra
  gather_facts: true
  vars:
    ib_ip: "{{ hostvars[inventory_hostname]['server_networks'][lln_name][0] }}"
  pre_tasks:
  - name: Enable passwordless sudo for wheel group
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'    
    become: yes
  roles:
  # Perform the mount action on all Ceph client nodes
  - role: stackhpc.os-manila-mount
    os_manila_mount_action: "mount"
    os_manila_mount_host: "{{ hostvars['localhost']['os_manila_mount_host'] }}"
    os_manila_mount_access_key: "{{ hostvars['localhost']['os_manila_mount_access_key'] }}"
    os_manila_mount_export: "{{ hostvars['localhost']['os_manila_mount_export'] }}"
    os_manila_mount_share_user: "home"
    os_manila_mount_pkgs_install: True
    os_manila_mount_path: "/var/mnt/ceph"
    os_manila_mount_user: "root"
    os_manila_mount_group: "root"
    os_manila_mount_fuse: False
  - configure-ib
  - mount-glusterfs
  - { role: singleplatform-eng.users, become: yes }
...
