#
# Copyright StackHPC, 2018
#
---
- hosts: container-infra
  gather_facts: yes
  vars:
    ib_ip: "{{ hostvars[inventory_hostname]['server_networks'][lln_name][0] }}"
  pre_tasks:
  - name: Enable passwordless sudo for wheel group
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'    
    become: yes
  roles:
  # Configure infiniband interface on the nodes
  - configure_ib
  - { role: singleplatform-eng.users, become: yes }
...
