---
#- include: setup.yml
#- include: ceph-client.yml
#- include: users.yml

- hosts: cluster
  remote_user: centos
  become: yes
  roles:
    - role: daliuge_runtime
      node_managers: "{{ cluster_node_mgr }}"

#- hosts: cluster_isl-mgr
#  remote_user: centos
#  become: yes
#  roles:
#    - role: daliuge_isl-mgr

#- hosts: cluster_node-mgr
#  remote_user: centos
#  become: yes
#  roles:
#    - role: daliuge_isl-mgr
