
- hosts:
  - cluster
  tasks:
    - shell:
        cmd: "openstack subnet show {{ item.subnet }} -c dns_nameservers -f json"
      with_items: "{{ cluster_net }}"
      when: "item.net == ext_name "
      register: dns_nameservers
      delegate_to: localhost # can't even use "openstack" here as the server's can't connect to it!
      run_once: true
    - debug:
        msg: "{{ (dns_nameservers.results[0].stdout | from_json).dns_nameservers[0] }}"
      run_once: true
    - copy:
        dest: /etc/resolv.conf
        content: |
          search alaskalocal novalocal
          nameserver {{ (dns_nameservers.results[0].stdout | from_json).dns_nameservers[0] }}
      become: true
