---
- name: Deploy glusterfs server
  hosts: cluster_glusterfs_server
  roles:
  - stackhpc.gluster-cluster

- name: Deploy glusterfs client
  hosts: cluster_glusterfs_client
  roles:
  - role: mount_glusterfs
    when:
    - gluster_src is defined
    - gluster_src is not none
...
