- name: Deploy a Gluster cluster with monitoring
  hosts: storage
  roles:
    - role: stackhpc.gluster-cluster
      gluster_cluster_volume_name: "{{ gluster_volume_name }}"
      gluster_cluster_block_devices:
        - sdb
        - sdc
        - sdd
      gluster_cluster_transport_interface: ib0
      gluster_cluster_transport_mode: rdma
      gluster_cluster_volume_options:
        cluster.nufa: 'on'
        performance.cache-size: '10GB'
    - role: stackhpc.monasca-agent
      become: yes
      keystone_url: "http://{{ controller_vip }}:5000/v3"
      monasca_user: root
      monasca_agent_user: "{{ monasca_agent_p3_username }}"
      monasca_agent_password: "{{ monasca_agent_p3_password }}"
      monasca_agent_project: "{{ project_name }}"
      monasca_agent_branch: stable/pike
      monasca_endpoint_type: public
      monasca_project_domain_name: Default
      monasca_user_domain_name: Default
      monasca_region_name: RegionOne
      monasca_service_type: monitoring
      monasca_agent_custom_plugin_repos:
        - "https://github.com/stackhpc/stackhpc-monasca-agent-plugins.git@master"

