---
- name: Deploy Monasca-rsyslog on Ceph nodes
  hosts: ceph
  become: true
  roles:
  - role: stackhpc.monasca-rsyslog
    monasca_rsyslog_api_auth:
      auth_url: "http://{{ controller_vip }}:5000"
      project: "{{ monasca_project_name }}"
      username: "{{ monasca_agent_username }}"
      password: "{{ monasca_agent_password }}"

- name: Deploy Monasca Agent
  hosts: ceph
  become: true
  roles:
  - role: stackhpc.monasca-agent
    keystone_url: "http://{{ controller_vip }}:5000/v3"
    monasca_user: root
    monasca_agent_user: "{{ monasca_agent_p3_username }}"
    monasca_agent_password: "{{ monasca_agent_p3_password }}"
    monasca_agent_project: "{{ project_name }}"
    monasca_agent_branch: stable/rocky  # Note: We use Rocky because monasca-common pulls in confluent-kafka on stein which doesn't build on arm cluster
    monasca_pip_extra_args: "-c https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt?h=stable/rocky"
    monasca_endpoint_type: public
    monasca_project_domain_name: Default
    monasca_user_domain_name: Default
    monasca_region_name: RegionOne
    monasca_service_type: monitoring
    monasca_log_level: INFO
    monasca_agent_system_only: true
    monasca_agent_custom_plugin_repos:
    - "https://github.com/stackhpc/stackhpc-monasca-agent-plugins.git"
