#
# Copyright StackHPC, 2018
#
---
- name: Deploy Prometheus Swarm monitoring service
  hosts: cluster_prometheus_swarm[0]
  gather_facts: no
  become: yes
  roles:
  - role: prometheus_swarm_service
