---
- name: Deploy nfs
  hosts:
  - cluster_nfs_server
  - cluster_nfs_client
  become: yes
  tasks:
  - include_role:
      name: stackhpc.nfs
    vars:
      nfs_enable:
        server: "{{ inventory_hostname in groups['cluster_nfs_server'] | first }}"
        clients: "{{ inventory_hostname in groups['cluster_nfs_client'] }}"
      nfs_server: "{{ groups['cluster_nfs_server'] | first }}"
      # other vars defined directly in the config:
      # nfs_export:
      # nfs_client_mnt_point: