---
# This uses nfs to export {{ alaska_homedir }} from the first login node to the compute nodes via the {{ ext_name }} network.

- name: Deploy nfs
  hosts:
  - cluster_nfs_server
  - cluster_nfs_client
  become: yes
  tasks:
  - include_role:
      name: stackhpc.nfs
    vars:
      nfs_enable:
        server: "{{ inventory_hostname in groups['cluster_nfs_server'] | first }}"
        clients: "{{ inventory_hostname in groups['cluster_nfs_client'] }}"
      nfs_server: "{{ hostvars[groups['cluster_nfs_server'] | first ]['server_networks'][ext_name][0] }}" # TODO: make interface configurable?
      nfs_export: "{{ alaska_homedir }}"
      nfs_client_mnt_point: "{{ alaska_homedir }}"
