---
# Prepare cluster
- import_playbook: setup.yml

# Prepare cluster
- import_playbook: latest-packages.yml

# Use mdadm to create software defined raid
- import_playbook: mdadm.yml

# Use mdadm to create software defined raid
- import_playbook: parted.yml


# Setup hyperconverged storage. Current clusterfs options are:
# - glusterfs
# - beegfs
# - <undefined>
- import_playbook: '{{ cluster_fs }}.yml'
  when: cluster_fs is defined

# Setup ceph mount
- import_playbook: manila-client.yml
  when: ceph_mount_enabled | default(false) | bool

# Add cluster users
- import_playbook: users.yml

# Add admin users
- import_playbook: cluster-admins.yml

# Install monitoring services
- import_playbook: monitoring.yml

# Cluster login setup
- import_playbook: slurm.yml
...
