---
# Prepare cluster
- import_playbook: setup.yml

# Setup ceph mount
- import_playbook: manila-client.yml

# Add cluster users
- import_playbook: users.yml

# Add admin users
- import_playbook: cluster-users.yml

# Setup hyperconverged glusterfs
- import_playbook: gluster-cluster.yml
- import_playbook: gluster-client.yml

- hosts: cluster_login
  remote_user: centos
  become: yes
  roles:
    - role: openhpc_control

- hosts: cluster_batch
  remote_user: centos
  become: yes
  roles:
    - role: openhpc_compute

- hosts: cluster
  remote_user: centos
  become: yes
  roles:
    - role: openhpc_runtime
      slurm_partitions: "{{ openhpc_slurm_partitions }}"
