---
- import_playbook: setup.yml
- import_playbook: manila-client.yml
- import_playbook: users.yml
- import_playbook: cluster-users.yml

- hosts: cluster_login
  remote_user: centos
  become: yes
  roles:
    - role: openhpc_control

- hosts: cluster_batch
  remote_user: centos
  become: yes
  roles:
    - role: openhpc_compute

- hosts: cluster
  remote_user: centos
  become: yes
  roles:
    - role: openhpc_runtime
      slurm_partitions: "{{ openhpc_slurm_partitions }}"
