- hosts: cluster
  tasks:
  - name: Create partitions
    parted:
      label: gpt
      state: present
      part_type: primary
      device: "{{ item.dev }}"
      part_start: "{{ item.start }}"
      part_end: "{{ item.end }}"
      number: "{{ item.number }}"
    with_items: "{{ partitions }}"
    # The `parted` module in Ansible version 2.4 and lower is buggy therefore this check is necessary
    when: ansible_version.full is version_compare('2.5', '>=')
    become: yes
