---
- src: stackhpc.cluster-infra
  version: v18.11.9
- src: stackhpc.monasca-agent
- src: stackhpc.monasca-rsyslog
- src: stackhpc.grafana-conf
- src: stackhpc.gluster-cluster
- src: stackhpc.os-container-infra
- src: stackhpc.os-manila-mount
- src: stackhpc.os-config
- src: stackhpc.beegfs
- src: singleplatform-eng.users
- src: mrlesmithjr.mdadm
- src: oasis-roles.kdump
...
