---
# Sorted by maintainer name, role name
- src: mrlesmithjr.mdadm
- src: oasis_roles.kdump
- src: singleplatform-eng.users
- src: stackhpc.os-container-infra
  version: v20.0.0
- src: stackhpc.os-manila-mount
  version: v19.6.1
- src: stackhpc.beegfs
  version: v19.8.2
- src: stackhpc.monasca-agent
  version: 1.0.4
- src: stackhpc.monasca-rsyslog
- src: stackhpc.grafana-conf
- src: stackhpc.gluster-cluster
- src: https://github.com/stackhpc/ansible-role-openhpc
  version: actions
  name: stackhpc.openhpc
- src: stackhpc.os-config
...
