---
# Apply generic setup configuration that is universally useful
- hosts: cluster
  become: yes
  roles:
    - role: oasis_roles.kdump
      kdump_package: kexec-tools
      kdump_conf_path: /etc/kdump.conf
      kdump_become_user: root
      kdump_crash_path: /var/crash
      kdump_core_collector_args: makedumpfile -l --message-level 1 -d 31
      when: kdump_enable | default(false)
    - role: cluster_setup
