---
- name: Install packages for BeeGFS client
  package:
    name: "{{ item }}"
    state: present
  become: True
  with_items:
  - "beegfs-client"
  - "beegfs-helperd"
  - "beegfs-utils"

- name: Ensure the BeeGFS client services are not running
  service:
    name: "{{ item }}"
    state: "stopped"
  become: True
  with_items:
  - "beegfs-helperd"
  - "beegfs-client"

- name: Detect the version of the running kernel
  command: "uname -r"
  register: kernel_version

- name: Define client kernel build for IB
  block:
  - name: Define client kernel build for IB
    lineinfile: 
      path: "/etc/beegfs/beegfs-client-autobuild.conf"
      regexp: "^buildArgs="
      line: "buildArgs=-j8 BEEGFS_OPENTK_IBVERBS=1"
  - name: Ensure kernel development headers are present
    package:
      name: "kernel-devel-{{ kernel_version.stdout }}"
      state: present
  become: True
  when: beegfs_rdma

- name: Ensure gcc is installed
  package:
    name: "gcc"
    state: present
  become: True

- name: Rebuild the BeeGFS client kernel module
  command: /etc/init.d/beegfs-client rebuild
  args:
    creates: "/lib/modules/{{kernel_version.stdout}}/updates/fs/beegfs_autobuild/beegfs.ko"
  become: True

- name: Run the BeeGFS client setup script
  command: "/opt/beegfs/sbin/beegfs-setup-client -m {{ beegfs_host_mgmt }} -f" 
  become: True

- name: Ensure the BeeGFS mount point is unmounted
  mount:
    path: "{{ beegfs_path_client }}"
    state: unmounted
  become: True

- name: Ensure the BeeGFS mount point exists
  file:
    path: "{{ beegfs_path_client }}"
    state: directory
  become: True

- name: Define BeeGFS mount point in mount config file
  template:
    src: "beegfs-mounts.conf.j2"
    dest: "/etc/beegfs/beegfs-mounts.conf"
    mode: 0644
  become: True 

- name: Specify connInterfacesFile
  lineinfile:
    path: /etc/beegfs/beegfs-client.conf
    regexp: "^connInterfacesFile"
    line: "connInterfacesFile           = /etc/beegfs/connInterfacesFile"
  become: True
