---
- name: Ensures BeeGFS meta service is not running
  service:
    name: "beegfs-meta"
    state: "stopped"
  become: True
  ignore_errors: True

- name: Install packages for BeeGFS metadata server
  package:
    name: beegfs-meta
    state: present
  become: True

- name: Create directory for BeeGFS metadata
  file:
    path: "{{ beegfs_path_meta }}"
    state: directory
  become: True

- name: Prepare metadata block storage
  block:
  - name: Ensure storage device is not currently mounted
    mount:
      path: "{{ beegfs_path_meta }}"
      state: unmounted
  - name: Format filesystem
    filesystem:
      dev: "{{ beegfs_dev_meta }}"
      fstype: "ext4"
      force: yes
  - name: Mount filesystem
    mount:
      src: "{{ beegfs_dev_meta }}"
      path: "{{ beegfs_path_meta }}"
      fstype: "ext4"
      state: mounted
  become: True
  when: beegfs_dev_meta is defined

- name: Run metadata service setup script
  command: "/opt/beegfs/sbin/beegfs-setup-meta -p {{ beegfs_path_meta }} -m {{ beegfs_host_mgmt }} -f"
  become: True
